"""
models/idea_schema.py
Pydantic models shared across all agents in the idea pipeline.
"""
from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Input ← Trend Analysis Agent
# ---------------------------------------------------------------------------

class TopicCluster(BaseModel):
    cluster_name: str
    papers: list[str] = Field(default_factory=list)


class TrendReport(BaseModel):
    trending_topics: list[str] = Field(default_factory=list)
    emerging_topics: list[str] = Field(default_factory=list)
    research_gaps: list[str] = Field(default_factory=list)
    topic_clusters: list[TopicCluster] = Field(default_factory=list)
    suggested_combinations: list[list[str]] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Idea — generated by Idea Generator Agent
# ---------------------------------------------------------------------------

class ProjectIdea(BaseModel):
    idea_title: str = Field(description="Short, catchy title (max 8 words).")
    problem_statement: str = Field(description="Real-world problem this project solves.")
    solution: str = Field(
        description=(
            "How the project solves the problem using modern AI methods. "
            "Must use correct terminology: RAG = Retrieval Augmented Generation, "
            "LLM = Large Language Model, KG = Knowledge Graph."
        )
    )
    technologies_used: list[str] = Field(description="3–5 specific AI/ML technologies or frameworks.")
    implementation_outline: list[str] = Field(description="4–6 ordered, concrete developer steps.")
    difficulty_level: Literal["Beginner", "Medium", "Advanced"]
    novelty_score: Literal["Low", "Medium", "High"]
    feasibility_score: Literal["Low", "Medium", "High"]
    generation_strategy: str = Field(description="Strategy used: Technology Fusion | Gap Exploitation | Emerging Tech | Cross-Cluster")
    target_users: list[str] = Field(description="E.g. Students, Developers, Researchers, Startups")


# ---------------------------------------------------------------------------
# Ranked Idea — produced by Idea Ranker Agent
# ---------------------------------------------------------------------------

class RankedIdea(BaseModel):
    idea_title: str
    novelty_score: float = Field(ge=0, le=10)
    feasibility_score: float = Field(ge=0, le=10)
    impact_score: float = Field(ge=0, le=10)
    complexity_score: float = Field(ge=0, le=10)
    final_score: float = Field(ge=0, le=10, description="0.4*Novelty + 0.3*Impact + 0.2*Feasibility - 0.1*Complexity")
    rank: int
    justification: str = Field(description="Short reason for the score.")


# ---------------------------------------------------------------------------
# Final Pipeline Output
# ---------------------------------------------------------------------------

class IdeaPipelineOutput(BaseModel):
    generated_ideas: list[ProjectIdea]
    ranked_ideas: list[RankedIdea]
